// Large collection of word-synonym pairs
const allWordPairs = [
    // Common adjectives
    ['happy', 'joyful'],
    ['sad', 'gloomy'],
    ['big', 'large'],
    ['small', 'tiny'],
    ['fast', 'quick'],
    ['smart', 'clever'],
    ['beautiful', 'gorgeous'],
    ['angry', 'furious'],
    ['brave', 'courageous'],
    ['tired', 'exhausted'],
    
    // More adjectives
    ['ancient', 'archaic'],
    ['awful', 'terrible'],
    ['bad', 'poor'],
    ['beautiful', 'attractive'],
    ['clean', 'spotless'],
    ['cold', 'chilly'],
    ['comfortable', 'cozy'],
    ['crazy', 'insane'],
    ['dangerous', 'hazardous'],
    ['dark', 'gloomy'],
    
    // Nouns
    ['friend', 'companion'],
    ['house', 'residence'],
    ['car', 'vehicle'],
    ['job', 'occupation'],
    ['money', 'wealth'],
    ['food', 'nourishment'],
    ['clothes', 'attire'],
    ['book', 'publication'],
    ['teacher', 'instructor'],
    ['student', 'pupil'],
    
    // Verbs
    ['run', 'sprint'],
    ['walk', 'stroll'],
    ['talk', 'speak'],
    ['eat', 'consume'],
    ['sleep', 'slumber'],
    ['work', 'labor'],
    ['play', 'frolic'],
    ['think', 'ponder'],
    ['look', 'observe'],
    ['listen', 'hear'],
    
    // More varied words
    ['achieve', 'accomplish'],
    ['begin', 'commence'],
    ['calm', 'peaceful'],
    ['defeat', 'conquer'],
    ['entire', 'whole'],
    ['famous', 'renowned'],
    ['genuine', 'authentic'],
    ['helpful', 'beneficial'],
    ['important', 'significant'],
    ['journey', 'voyage'],
    
    // Challenging words
    ['abundant', 'plentiful'],
    ['benevolent', 'generous'],
    ['capricious', 'unpredictable'],
    ['diligent', 'hardworking'],
    ['eloquent', 'articulate'],
    ['furtive', 'secretive'],
    ['gregarious', 'sociable'],
    ['haphazard', 'random'],
    ['imminent', 'impending'],
    ['jovial', 'cheerful'],
    
    // Academic words
    ['analyze', 'examine'],
    ['concept', 'idea'],
    ['debate', 'discussion'],
    ['evidence', 'proof'],
    ['framework', 'structure'],
    ['hypothesis', 'theory'],
    ['integrate', 'combine'],
    ['justify', 'validate'],
    ['methodology', 'approach'],
    ['paradigm', 'model'],
    
    // Technology words
    ['algorithm', 'procedure'],
    ['browser', 'navigator'],
    ['connectivity', 'connection'],
    ['database', 'repository'],
    ['encryption', 'coding'],
    ['firewall', 'barrier'],
    ['interface', 'connection'],
    ['network', 'system'],
    ['protocol', 'convention'],
    ['wireless', 'cordless']
]; 

// Word pairs organized by level of difficulty for Words of Havoc
// Each level has a name, tagline, and word pairs

const levels = [
    {
        name: 'Word Rookie',
        tagline: 'Every siege starts with a simple word.',
        pairs: [
            // Basic, common words (Level 1)
            ['happy', 'joyful'],
            ['sad', 'gloomy'],
            ['big', 'large'],
            ['small', 'tiny'],
            ['fast', 'quick'],
            ['smart', 'clever'],
            ['beautiful', 'gorgeous'],
            ['angry', 'furious'],
            ['brave', 'courageous'],
            ['tired', 'exhausted'],
            ['cold', 'chilly'],
            ['hot', 'warm'],
            ['funny', 'humorous'],
            ['kind', 'gentle'],
            ['nice', 'pleasant'],
            ['rich', 'wealthy'],
            ['poor', 'needy'],
            ['young', 'youthful'],
            ['old', 'elderly'],
            ['new', 'recent'],
            ['good', 'great'],
            ['bad', 'terrible'],
            ['strong', 'powerful'],
            ['weak', 'feeble'],
            ['loud', 'noisy'],
            ['quiet', 'silent'],
            ['healthy', 'fit'],
            ['sick', 'ill'],
            ['clean', 'tidy'],
            ['dirty', 'filthy'],
            ['easy', 'simple'],
            ['hard', 'difficult'],
            ['thin', 'slim'],
            ['fat', 'plump'],
            ['bright', 'brilliant'],
            ['dark', 'dim'],
            ['busy', 'occupied'],
            ['free', 'available'],
            ['famous', 'celebrated'],
            ['unknown', 'anonymous'],
            ['safe', 'secure'],
            ['dangerous', 'hazardous'],
            ['right', 'correct'],
            ['wrong', 'incorrect'],
            ['true', 'accurate'],
            ['false', 'untrue'],
            ['early', 'prompt'],
            ['late', 'tardy'],
            ['open', 'unlocked'],
            ['closed', 'shut']
        ]
    },
    {
        name: 'Vocab Apprentice',
        tagline: 'Learning the craft of word warfare.',
        pairs: [
            // Intermediate words (Level 2)
            ['ancient', 'archaic'],
            ['awful', 'terrible'],
            ['bad', 'poor'],
            ['beautiful', 'attractive'],
            ['clean', 'spotless'],
            ['comfortable', 'cozy'],
            ['crazy', 'insane'],
            ['dangerous', 'hazardous'],
            ['dark', 'gloomy'],
            ['friend', 'companion'],
            ['house', 'residence'],
            ['car', 'vehicle'],
            ['job', 'occupation'],
            ['money', 'wealth'],
            ['food', 'nourishment'],
            ['clothes', 'attire'],
            ['book', 'publication'],
            ['teacher', 'instructor'],
            ['student', 'pupil'],
            ['run', 'sprint'],
            ['walk', 'stroll'],
            ['talk', 'speak'],
            ['eat', 'consume'],
            ['sleep', 'slumber'],
            ['work', 'labor'],
            ['play', 'frolic'],
            ['think', 'ponder'],
            ['look', 'observe'],
            ['listen', 'hear'],
            ['afraid', 'fearful'],
            ['angry', 'irate'],
            ['answer', 'reply'],
            ['begin', 'commence'],
            ['better', 'superior'],
            ['break', 'fracture'],
            ['bring', 'deliver'],
            ['build', 'construct'],
            ['busy', 'engaged'],
            ['calm', 'tranquil'],
            ['certain', 'positive'],
            ['change', 'alter'],
            ['chief', 'main'],
            ['clear', 'transparent'],
            ['common', 'ordinary'],
            ['complete', 'finish'],
            ['complex', 'complicated'],
            ['conceal', 'hide'],
            ['concern', 'worry'],
            ['consider', 'contemplate'],
            ['continue', 'proceed']
        ]
    },
    {
        name: 'Thesaurus Warrior',
        tagline: 'Meaning must fall.',
        pairs: [
            // Advanced words (Level 3)
            ['achieve', 'accomplish'],
            ['begin', 'commence'],
            ['calm', 'peaceful'],
            ['defeat', 'conquer'],
            ['entire', 'whole'],
            ['famous', 'renowned'],
            ['genuine', 'authentic'],
            ['helpful', 'beneficial'],
            ['important', 'significant'],
            ['journey', 'voyage'],
            ['knowledge', 'information'],
            ['liberty', 'freedom'],
            ['magnificent', 'splendid'],
            ['necessary', 'essential'],
            ['obvious', 'evident'],
            ['persistent', 'tenacious'],
            ['question', 'interrogate'],
            ['reliable', 'dependable'],
            ['sufficient', 'adequate'],
            ['triumphant', 'victorious'],
            ['understand', 'comprehend'],
            ['vibrant', 'brilliant'],
            ['worried', 'anxious'],
            ['yearning', 'longing'],
            ['zealous', 'enthusiastic'],
            ['analyze', 'examine'],
            ['concept', 'idea'],
            ['debate', 'discussion'],
            ['evidence', 'proof'],
            ['framework', 'structure'],
            ['hypothesis', 'theory'],
            ['integrate', 'combine'],
            ['justify', 'validate'],
            ['methodology', 'approach'],
            ['paradigm', 'model'],
            ['abundant', 'plentiful'],
            ['benevolent', 'generous'],
            ['capricious', 'unpredictable'],
            ['diligent', 'hardworking'],
            ['eloquent', 'articulate'],
            ['feasible', 'possible'],
            ['gregarious', 'sociable'],
            ['haphazard', 'random'],
            ['imminent', 'impending'],
            ['judicious', 'wise'],
            ['keen', 'eager'],
            ['lucid', 'clear'],
            ['meticulous', 'precise'],
            ['notorious', 'infamous'],
            ['optimistic', 'hopeful']
        ]
    },
    {
        name: 'Semantic Reaper',
        tagline: 'Aim where you smell dread. The right words fear you.',
        pairs: [
            // Expert level words (Level 4)
            ['abundant', 'copious'],
            ['benevolent', 'charitable'],
            ['capricious', 'fickle'],
            ['diligent', 'assiduous'],
            ['eloquent', 'fluent'],
            ['furtive', 'secretive'],
            ['gregarious', 'convivial'],
            ['haphazard', 'chaotic'],
            ['imminent', 'looming'],
            ['jovial', 'cheerful'],
            ['labyrinth', 'maze'],
            ['munificent', 'generous'],
            ['nefarious', 'villainous'],
            ['obsequious', 'servile'],
            ['pernicious', 'harmful'],
            ['quiescent', 'dormant'],
            ['recalcitrant', 'defiant'],
            ['sagacious', 'wise'],
            ['truculent', 'aggressive'],
            ['ubiquitous', 'omnipresent'],
            ['vacillate', 'waver'],
            ['winsome', 'charming'],
            ['xenophobic', 'intolerant'],
            ['yearning', 'craving'],
            ['zealous', 'passionate'],
            ['abstruse', 'obscure'],
            ['cacophony', 'dissonance'],
            ['deleterious', 'harmful'],
            ['ebullient', 'exuberant'],
            ['fastidious', 'meticulous'],
            ['garrulous', 'talkative'],
            ['hegemony', 'dominance'],
            ['iconoclast', 'rebel'],
            ['juxtapose', 'contrast'],
            ['kaleidoscopic', 'variegated'],
            ['loquacious', 'talkative'],
            ['mellifluous', 'melodious'],
            ['neophyte', 'beginner'],
            ['obfuscate', 'confuse'],
            ['parsimonious', 'frugal'],
            ['querulous', 'complaining'],
            ['recondite', 'esoteric'],
            ['surreptitious', 'clandestine'],
            ['trepidation', 'apprehension'],
            ['unctuous', 'ingratiating'],
            ['venerate', 'revere'],
            ['whimsical', 'capricious'],
            ['xenial', 'hospitable'],
            ['yoke', 'bind'],
            ['zeitgeist', 'spirit']
        ]
    }
];

// Make levels available globally
window.levels = levels; 